# Generated by Django 3.2 on 2022-02-17 23:24

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=200, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(max_length=200, verbose_name='combustible')),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('make_id', models.AutoField(primary_key=True, serialize=False)),
                ('make_type', models.CharField(max_length=200, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_type', models.CharField(max_length=200, verbose_name='Modelo')),
                ('make_id', models.ForeignKey(db_column='make_id', on_delete=django.db.models.deletion.RESTRICT, related_name='Models', to='api.make', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_type', models.CharField(max_length=200, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('transmission_id', models.AutoField(primary_key=True, serialize=False)),
                ('transmission_type', models.CharField(max_length=200, verbose_name='Transmisión')),
            ],
        ),
        migrations.CreateModel(
            name='SalePost',
            fields=[
                ('salePost_id', models.AutoField(primary_key=True, serialize=False)),
                ('salePost_description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('salePost_yearModel', models.DateField(verbose_name='Año modelo')),
                ('salePost_kilometer', models.IntegerField(verbose_name='Kilometraje')),
                ('salePost_cylinder', models.CharField(max_length=200, verbose_name='Cilindrada')),
                ('salePost_door', models.IntegerField(verbose_name='Número de puertas')),
                ('salePost_color', models.CharField(max_length=200, verbose_name='Color')),
                ('salePost_price', models.IntegerField(verbose_name='Precio dólares')),
                ('salePost_newCar', models.BooleanField(verbose_name='Auto nuevo')),
                ('salePost_photo', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('salePost_datePost', models.DateTimeField(null=True, verbose_name='Fecha de publicación')),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, to='api.category', verbose_name='Categoria')),
                ('fuel_id', models.ForeignKey(db_column='fuel_id', on_delete=django.db.models.deletion.RESTRICT, to='api.fuel', verbose_name='Combustible')),
                ('model_id', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.RESTRICT, to='api.model', verbose_name='Modelo')),
                ('region_id', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.RESTRICT, to='api.region', verbose_name='Region')),
                ('tranmission_id', models.ForeignKey(db_column='transmission_id', on_delete=django.db.models.deletion.RESTRICT, to='api.transmission', verbose_name='Transmisión')),
                ('usu_id', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ExtentUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_dni', models.IntegerField(blank=True, null=True)),
                ('user_cellphone', models.IntegerField(blank=True, null=True)),
                ('usu_id', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
