# Generated by Django 3.2 on 2022-02-04 00:05

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_type', models.CharField(max_length=200, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_year', models.DateField(verbose_name='Año modelo')),
                ('car_kilometer', models.IntegerField(verbose_name='Kilometraje')),
                ('car_color', models.CharField(max_length=200, verbose_name='Color')),
                ('car_cylinder', models.CharField(max_length=200, verbose_name='Motor')),
                ('car_photo', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('brand_id', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.RESTRICT, to='api.brand', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=200, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(max_length=200, verbose_name='combustible')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_type', models.CharField(max_length=200, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('transmission_id', models.AutoField(primary_key=True, serialize=False)),
                ('transmission_type', models.CharField(max_length=200, verbose_name='Transmisión')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_price', models.IntegerField(verbose_name='Precio')),
                ('sale_date', models.DateTimeField(null=True, verbose_name='Fecha')),
                ('sale_newused', models.BooleanField()),
                ('car_id', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.RESTRICT, to='api.car', verbose_name='Carro')),
                ('region_id', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.RESTRICT, to='api.region', verbose_name='Region')),
                ('usu_id', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_type', models.CharField(max_length=200, verbose_name='Modelo')),
                ('brand_id', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.RESTRICT, to='api.brand', verbose_name='Marca')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, to='api.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_id',
            field=models.ForeignKey(db_column='fuel_id', on_delete=django.db.models.deletion.RESTRICT, to='api.fuel', verbose_name='Combustible'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.RESTRICT, to='api.model', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='tranmission_id',
            field=models.ForeignKey(db_column='transmission_id', on_delete=django.db.models.deletion.RESTRICT, to='api.transmission', verbose_name='Transmisión'),
        ),
    ]
