# Generated by Django 3.2 on 2022-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=200)),
                ('dni', models.IntegerField(max_length=8)),
                ('celular', models.IntegerField(max_length=9)),
            ],
        ),
    ]
